### ISSUE TITLE
 Port score to OpenJDK 11

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/score#158]
We received this message from user: 
```
As per this document, the installation of icgc storage client requires the installation of Oracle Java 8.
https://docs.icgc.org/download/guide/#score-client-usage  

# Install Oracle JDK 8 sudo addapt-repository ppa:webupd8team/java sudo aptget update sudo apt-get upgrade y sudo aptget install y oracle-java8-installer oracle-java8set-default 

However, Oracle recently has taken away this general license: https://launchpad.net/~webupd8team/+archive/ubuntu/java
```

Score is currently using Oracle JDK 8, however the open licence for this has been removed. We need to change to an open package that users can install. 

- Update the SONG instructions. Tell Hardeep to test, and notify the end user.

**Comment by andricDu** [comment]
### Version Change 8 -> 11
- lombok needs to be updated
- careful with illegal access and reflection

### Vendor Change OracleJDK -> OpenJDK
- proprietary oracle extensions will need to be replaced if any are there
