### ISSUE TITLE
BUG - misleading message on JDK Version

### ISSUE THREAD

**Issue by andricDu** [overture-stack/score#167]
The message for when using the wrong java version is incorrect. 

## Description
The current error message:
```
root@petagene:~/score-client-2.0.0/bin# ./score-client download --profile collab --manifest 362758b7-0041-45da-a99e-6989f7ca5020
Java not found. The Storage Client requires JDK 1.8
```

## Expected Behaviour
It should inform the user that OpenJDK 11 is required. 

## Possible Fix
Update the message to include the new information. 

## Steps to Reproduce
Try running score where there is no java installed.

**Comment by rosibaj** [comment]
@andricDu to release today!
