### ISSUE TITLE
BUG: Cannot Upload objects with Score

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/score#170]
- Cannot upload files in score
- It gets past the SONG communication, but will not complete upload 
- after that it fails for an unknown reason

## Exit criteria 
- [ ] Can use score-client to successfully upload an object that already has the metadata in song

**Comment by KevinFHartmann** [comment]
I was wrong. You *can* upload objects with Score. Rob demonstrated a configuraton that works. :-(

**Comment by rosibaj** [comment]
@KevinFHartmann @rtisma just for future reference, can you guys please comment what the issue was here?

**Comment by KevinFHartmann** [comment]
I didn't have the configuration set up exactly right; we suspect that I didn't have the right files in the right place (possible the wrong placement of the sentinel file?) in Minio.

**Comment by KevinFHartmann** [comment]
We didn't fix my configuration so much as replace it with a working one; so I'm still working out exactly which parts were the parts that didn't work -- but at least now we have a configuration that *does* work!
