### ISSUE TITLE
BUG - 404 for various collab metadata

### ISSUE THREAD

**Issue by jmimico** [overture-stack/score#172]
client = score
server = radosgw (collab)
Rados returning 404 to score

Examples:
/oicr.icgc.state.24/data/95899fd4-8374-58fa-a090-e6d60ea6601b.meta
/oicr.icgc.state.24/data/95899fd4-8374-58fa-a090-e6d60ea6601b.meta

**Comment by rtisma** [comment]
Could not recreate the issue. I was able to successfully download the objectId `893ad4de-6d18-56aa-b45d-58caa06d6966`, which has the filename `999bc0fb517ea2ca91fc88b5c9676295.bam`, along with the index file with objectId `95899fd4-8374-58fa-a090-e6d60ea6601b` which has the filename `999bc0fb517ea2ca91fc88b5c9676295.bam.bai`
