### ISSUE TITLE
Fix score-client profile management

### ISSUE THREAD

**Issue by rtisma** [overture-stack/score#177]
Currently, there is aws and collab profiles, which have baked in values. If a profile is not specified, then the `storage.url` and `metadata.url` values from the properties file are not picked up. If the `--profile` flag is not specified, should default to this order:
1. ENV variables
2. properties files variables. 

If `--profile aws` is specified, should default to this order:
1. ENV variables
2. properties files variables
3. baked in configs for `aws` profile (song aws and score aws) 

the following properties are of interest

metadata.url
storage.url
accessToken

**Comment by KevinFHartmann** [comment]
The --profile setting corresponds to the storage.profile java property and the environment variable STORAGE_PROFILE, defaulting to aws.

It is currently being used to set which *Spring Boot* profile(s) should be run.

This is misleading, and needs fixing as part of this ticket.
