### ISSUE TITLE
BUG - Unable to download files belong to a Song analysis with a big number of files  

### ISSUE THREAD

**Issue by lindaxiang** [overture-stack/score#244]
## Description

If the Song analysis only contains handful files, the downloading does not have problem. 
However if there are a big number of files attached to the Song analysis, the downloading is stuck.

## Steps to Reproduce
1. Given the following Song analysis which has 70 files attached to it: 
`https://song.rdpc-qa.cancercollaboratory.org/studies/TEST-PR/analysis/46a6d102-19f8-4ba2-a6d1-0219f83ba28e`

[46a6d102-19f8-4ba2-a6d1-0219f83ba28e.txt](https://github.com/overture-stack/score/files/5393916/46a6d102-19f8-4ba2-a6d1-0219f83ba28e.txt)

1. Run the command:
`docker run -i --rm  -u $(id -u):$(id -g) -e ACCESSTOKEN=$ACCESSTOKEN -e METADATA_URL=$METADATA_URL -e STORAGE_URL=$STORAGE_URL -v "$PWD":"$PWD" -w "$PWD" overture/score:latest /score-client/bin/score-client --profile collab download --study-id TEST-PR --analysis-id 46a6d102-19f8-4ba2-a6d1-0219f83ba28e --output-dir .`

Also verified with the score-client command:
```
 score-client-5.1.0/bin/score-client download --analysis-id 46a6d102-19f8-4ba2-a6d1-0219f83ba28e --study-id TEST-PR --output-dir ./testing_argo_qa/downloaded_files
Downloading...    
```

1. The downloading is stuck by just showing: 
`Downloading...`

## Your Environment

* Version used: overture/score:latest   3.0.1
* Operating System and version (desktop or mobile): MacOS, Linux

Rosi's test version
* Version used: score-client-5.1.0/
* Operating System and version (desktop or mobile): Linux Subsystem on Windows

**Comment by lindaxiang** [comment]
@rtisma @rosibaj  For your information, this happens to the current RDPC data: 
https://song.rdpc.cancercollaboratory.org/studies/PACA-CA/analysis/fa2cc829-c646-4719-acc8-29c6465719e4

As this analysis has 20+ objects attached to it, no objects can be successfully downloaded. 
Version used: overture/score:latest 5.0.0

**Comment by rosibaj** [comment]
@lindaxiang what exact command ar you using to download the data so i can try as well?

**Comment by lindaxiang** [comment]
@rosibaj , I was using latest docker version of score. this is command I used inside the docker to download one object:
`/score-client/bin/score-client download --object-id 4fe66910-0260-50f5-99e3-f80983038ac4 --study-id PACA-CA --output-dir .`

**Comment by rosibaj** [comment]
At least diagnose the issue; regroup when we know the problem and resolve as new tickets or here

**Comment by jaserud** [comment]
The issues is actually in SONG server's entities endpoint. The paging isn't working correctly.

For example if you go to page 0 or 436, you always get the first 20 entities or page 0:
https://song.rdpc-qa.cancercollaboratory.org/entities?gnosId=46a6d102-19f8-4ba2-a6d1-0219f83ba28e&size=2000&page=0
https://song.rdpc-qa.cancercollaboratory.org/entities?gnosId=46a6d102-19f8-4ba2-a6d1-0219f83ba28e&size=2000&page=436
```

  ],
  "pageable": {
    "offset": 0,
    "sort": {
      "unsorted": false,
      "sorted": true,
      "empty": false
    },
    "pageSize": 20,
    "pageNumber": 0,
    "paged": true,
    "unpaged": false
  },
  "totalPages": 4,
  "last": false,
  "totalElements": 70,
  "first": true,
  "sort": {
    "unsorted": false,
    "sorted": true,
    "empty": false
  },
  "numberOfElements": 20,
  "size": 20,
  "number": 0,
  "empty": false
```

**Comment by rosibaj** [comment]
@jaserud can we get this deployed to Dev or QA for testing today?

**Comment by jaserud** [comment]
@rosibaj the fix in song-server is now deployed to argo rdpc-dev... The fix from the SONG side looks good. I was able to download all 70 files in TEST-PR analysis 92453d02-841a-4c72-853d-02841afc72bd by running this command:
```
docker run -i --rm \
  --network host \
  -u $(id -u):$(id -g) \
  -e ACCESSTOKEN=****** \
  -e METADATA_URL=https://song.rdpc-dev.cancercollaboratory.org \
  -e STORAGE_URL=https://score.rdpc-dev.cancercollaboratory.org \
  -v "$PWD":"$PWD" \
  -w "$PWD" \
  overture/score:latest \
  /score-client/bin/score-client --profile collab download --study-id TEST-PR --analysis-id 92453d02-841a-4c72-853d-02841afc72bd --output-dir ./score-bugging
```

A side note about the clients performance/messaging, while running this it took some time just sitting in the "Downloading..." state before the downloads actually started. I actually thought my fix didn't work and had to run the client in debug mode to see that it actually was working. Maybe there should be an in between "Loading..." state or similar since its not actually downloading :thinking:. Or we might need to look into why it takes so much time because an array of 70 ids shouldn't take this long...from what I can tell stepping through the code there are a lot of nested looping.

**Comment by rosibaj** [comment]
Note: this cannot move forward until the song changes that are in overture dev are successfulyl deployed in argo-dev, approved and ready to move to argo-qa. 
Those are being tested now.

**Comment by rosibaj** [comment]
@lindaxiang can you please verify that you can complete the original download in qa before i close this ticket?

**Comment by lindaxiang** [comment]
@rosibaj , I can confirm I can complete the download of 70 files belong to `https://song.rdpc-qa.cancercollaboratory.org/studies/TEST-PR/analysis/46a6d102-19f8-4ba2-a6d1-0219f83ba28e` in QA now. 
The download behaviour is exactly what Jaser described above. 
Great job! @jaserud !
