### ISSUE TITLE
Update score-server to have separate download and upload system scopes

### ISSUE THREAD

**Issue by rtisma** [overture-stack/score#257]
## Problem

Currently, score is not backwards compatible for ICGC (atleast easily). In previous icgc,  if users  has `collab.READ`, they could download from any study. If they had `collab.WRITE` they could upload to any study. 

Using the current implementation, there is no way to achieve similar functionality, easily. Alternatively, if there are N studies, then for any user that previously has collab.READ, N scopes with collab.<studyId>.READ could be created (which could mean N policies, 1 system read group, and N groupPermissions with .READ mask for each of N policies with that 1 system read group, and then adding all users to that 1 system read group).

## Details
if the `system.scope = someName.someSuffix`, and a user has that system scope, they can read **AND** write across all studies. There is no way to allow a set of user to only read (download) across all studies and another set of users to write (upload) across all studies.

https://github.com/overture-stack/score/blob/4.0.0/score-server/src/main/java/bio/overture/score/server/security/UploadScopeAuthorizationStrategy.java#L43
https://github.com/overture-stack/score/blob/4.0.0/score-server/src/main/java/bio/overture/score/server/security/UploadScopeAuthorizationStrategy.java#L51-L53

https://github.com/overture-stack/score/blob/4.0.0/score-server/src/main/java/bio/overture/score/server/security/DownloadScopeAuthorizationStrategy.java#L43-L45

The DownloadScopeAuthorizationStrategy calls the UploadScopeAuthorizationsStrategy's `verifyOneOfSystemScope` method, meaning if one of the user's scopes matched the systemScope, they can download **AND** upload to **ANY** study.

## Solution
Separate system.scope into 2 categories: upload and download. So the score-server config would look like:
```yaml
auth:
  server:
    scope:
      download:
        system: aws.download
        study:
          prefix: aws.
          suffix: .download
      upload:
        system: aws.upload
        study:
          prefix: aws.
          suffix: .upload
```

### Scenarios:
1. User has `aws.upload` scope
User can upload and download from **ANY** study. This is the highest privilege

2. User has `aws.PACA-CA.upload` scope
User can upload and download to **ONLY** the PACA-CA study.

3. User has `aws.download` scope
User can **ONLY** download from **ANY** study.

4. User has `aws.PACA-CA.download` scope
User can **ONLY** download from **ONLY** the PACA-CA study.

**Comment by rosibaj** [comment]
@rtisma i think you have deployed so we can close this now?
