### ISSUE TITLE
Feature Request: Add JWT Authorization to Score-server 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/score#267]
Score-server use API-Key authorization currently. We need to extend to also respond to a JWT (application or user level).  These are the specs for how the JWT will be formatted: https://wiki.oicr.on.ca/display/OV/Application+Level+Authorization 

- Score uses Method Security which means it will work a little different than other apps we have done. 
- for the method security will need to check `between` API-Key or JWT and know which type of authorization will be used 
- will need to refactor to add logic to the component to help distinguish between API-Key and JWT

**Comment by rosibaj** [comment]
@rtisma @andricDu anyway we can get a review before the next sprint here? looks outstanding from github

**Comment by rtisma** [comment]
@rosibaj  this is missing tests. Once my PR is approved, the testing infra can be reused.
