### ISSUE TITLE
Implement presigned url rewritable domain

### ISSUE THREAD

**Issue by rtisma** [overture-stack/score#277]
# Objective
Refer to https://wiki.oicr.on.ca/display/OV/DMS+Installer+Technical+Specs#DMSInstallerTechnicalSpecs-MinioObjectURLRewrite

TLDR: score should be able to replace the server url with whatever is configured in the application.yml 

# Outcome
When the command `curl -XGET https://score.example.org/download/<objectId>` is executed, the response should contain presigned urls starting with `https://domain-from-config.example.org/<presignedUrlParams>`.

**Comment by b-f-chan** [comment]
Tested in local and server mode with MinIo using path-based gateway solution.  MinIo working, closing.
