### ISSUE TITLE
refactor getObjectIdsByAnalysisId to use GET /entities?gnosId=

### ISSUE THREAD

**Issue by hlminh2000** [overture-stack/score#280]
To support https://wiki.oicr.on.ca/display/icgcargotech/File+Download+Access+Control.

Refactor 1 function in score-client, to depend on the GET /entities?gnosId= endpoiont and not the `GET /studies/{studyId}/analysis/{analysisId}`

This is needed for Argo' implementation of access-controlled file download.

## Detailed Description
https://github.com/overture-stack/score/blob/5e15fb92aa84fb81956754595af1024d5c6d7ce5/score-client/src/main/java/bio/overture/score/client/metadata/legacy/LegacyMetadataClient.java#L132

**Comment by rtisma** [comment]
After discussing with @rosibaj , we want to go the opposite direction: deprecate the `/entities?gnosId` usage infavour of the other one. The following ticket outline what needs to be done
https://github.com/overture-stack/score/issues/281

Will close this ticket as wont-do

**Comment by akachru-github** [comment]
Consider: we tend to use newer versions of Score with legacy versions of Song. This change would support backward compatibility for new Score and older versions of Song.

**Comment by jaserud** [comment]
The entiies endpoint in metadata server needs to be able to filter on gnosId. The gateway currently has a bug that prevents this from working with it: https://github.com/icgc-argo/platform-api/issues/457.

**Comment by rosibaj** [comment]
@jaserud can we please get a release for this today?

**Comment by jaserud** [comment]
Released! Available in version 5.8.0: https://artifacts.oicr.on.ca/artifactory/dcc-release/bio/overture/score-client/5.8.0/

**Comment by rosibaj** [comment]
excellent - thank you @jaserud !
