### ISSUE TITLE
refactor getIndexEntity to use getEntitiesByAnalysisId

### ISSUE THREAD

**Issue by rtisma** [overture-stack/score#281]
Currently, the getIndexEntity method in the score client is using the `/entities?gnosId=` to get all files for an analysis. This should be replaced by a new method called `getEntitesByAnalysisId`. This will then allow us to retire the `/entities?gnosId=` usage throughout score-client. 

https://github.com/overture-stack/score/blob/develop/score-client/src/main/java/bio/overture/score/client/metadata/legacy/LegacyMetadataService.java#L47

**Comment by akachru-github** [comment]
Consider: we tend to use newer versions of Score with legacy versions of Song. This change would support backward compatibility for new Score and older versions of Song.

Because of this, we will be going ahead with https://github.com/overture-stack/score/issues/280 instead of this issue.
