### ISSUE TITLE
Feature Request: Ability to define write location of temp files in score client 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/score#302]
## Detailed Description

This issue was discovered with the  MUTO-INTL group while attempting to initiate their uploads.

- When the `score-client upload --manifest <manifest name here>` was run, and error of `An upload is already in progress` was reported.  
- This did not make sense, as this was the first time the upload was attempted. It should have gone through.
- After examining the client logs, we could see that the user was rejected from writing a temp file that locally tracks the progress of the upload to the directory where the upload files exist. 
- The bioinformatics user has read, but not write access to the directory where BAM files are stored.  This would be a **common use case** for users of HPC or data storage systems; they may not always have write access to the actual file directory. 

## Possible Implementation
location: https://github.com/overture-stack/score/blob/75253a671778df882fd2508ff35768b15224df39/score-client/src/main/java/bio/overture/score/client/upload/UploadStateStore.java#L45

**Comment by jaserud** [comment]
Testing:
- go through the song score dance by `submitting` an analysis and preparing the `manifest`
- make the folder with all of the files to upload and manifest `read only` (usually in the folder's properties in most OS)
- try to upload via the latest client (5.4.0+), and you should get a access denied exception/error
- set the env variable in the score client app properties`client.uploadStateDir` (see example config below), to a dir that has `write` access
- then upload via score client, should get no errors for access denied

example config
```
metadata.url=https://song.rdpc-dev.cancercollaboratory.org/
storage.url=https://score.rdpc-dev.cancercollaboratory.org/
client.uploadStateDir=/dir/with/write/access/scratch #absolute path
client.accessToken=****SET YOUR TOKEN HERE****
```

**Comment by jaserud** [comment]
new client tar: https://artifacts.oicr.on.ca/artifactory/dcc-release/bio/overture/score-client/5.4.0/score-client-5.4.0-dist.tar.gz

**Comment by akachru-github** [comment]
A new client has been made available.
