### ISSUE TITLE
score-client as singularity container on HPC (SLURM). Solved but unstable

### ISSUE THREAD

**Issue by yazbeck** [overture-stack/score#327]
Dear all,
I would like to share my experience in using score-client as a singularity container.
**Note:** _you may get an error to make sure you are connected to the server. If you are requesting from the correct server (in my case: export STORAGE_PROFILE=collab ), then ignore and just hit download again._

General steps:
It is neccessary to build with **--sandbox** and run it as **--writable** to be able to read its own log files, and also sometimes you need to creat a data file inside the built singularity folder to be able to mount (bind) a local path to the container, so:
- singularity build --sandbox ICGCdownload/ docker://overture/score
- _If needed:_ cd ICGCdownload/; mkdir data/
- cd ICGCdownload/score-client/conf/ and edit the file **application.properties** to edit the access token and other fields (this can be also done inside the container using bash if you want)
- singularity shell -B local-file:/data --writable ICGCdownload
- test: score-client --version should give you something like:
SCORE Client
  Version: 5.6.0
  Built:   11.03.2016 @ 11:23:08 EST
  Contact: dcc-support@icgc.org

- Here you go!

**_In case no internet inside the container:_** In my case, the container was connected directly to /etc/resolv.conf on the system (some cases might need /tmp/resolv.conf). You might have that the container is not connected to internet. Then you need to check if the containers /etc/resolv.conf, /tmp/resolv.conf or sometimes in /var/tmp/resolv.conf are connected to the system resolv.conf. This can be solved for instance by mounting the directories (e.g. -B /tmp/:/tmp).

**PS:** I can also offer solution for EGApy3 download client if needed!

**Comment by joneubank** [comment]
Thank you contributing back your experience. I am closing this issue as there is no clear action to take here.
