### ISSUE TITLE
Upgrade spring boot service

### ISSUE THREAD

**Issue by ghost** [overture-stack/score#340]

**Comment by joneubank** [comment]
Similar work was done in SONG, this may be a useful model for updating JWT and API key validation using the upgraded Spring WebSecurity version https://github.com/overture-stack/SONG/pull/768

**Comment by joneubank** [comment]
Closing as no description given, including target versions and the motivations for the change. A review of dependency versions and upgrade to modern Spring versions would be valuable but will be tracked in another ticket.
