### ISSUE TITLE
Make a formal release for `score-client`

### ISSUE THREAD

**Issue by lindaxiang** [overture-stack/score#357]
This release will contain the bug fixes for these issues: 

https://github.com/icgc-argo/workflow-roadmap/issues/229
https://github.com/icgc-argo/workflow-roadmap/issues/333
https://github.com/icgc-argo/workflow-roadmap/issues/346

I’ve tested the data download from `rdpc-qa` with docker container and version:
```
"score_container":"overture/score",
"score_container_version": "edge",
```
and the downloading works without issue.

Please make a formal release for this version of `score-client` from `ghcr.io`, so that the workflow is able to set the params of container and version properly.

## Exit Criteria
1. THe latest score pod is deployed and running in rdpc dev, qa, prod.
2. release note is updated: https://github.com/overture-stack/score/releases
3. Users are able to download the latest client from https://hub.docker.com/r/overture/score/tags

**Comment by Buwujiu** [comment]
Will plan for a release once #229 and #333 are complete.

**Comment by joneubank** [comment]
We need to update our release requirements to not lsit dockerhub. We now host all our published packages in ghcr: https://github.com/orgs/overture-stack/packages .

Score 5.9.0 is hosted here: ghcr.io/overture-stack/score:5.9.0

**Comment by joneubank** [comment]
Correction to myself: We are currently publishing in both places: https://hub.docker.com/layers/overture/score/5.9.0/images/sha256-06f58985637eb3add727e43f5ace432114608fa2a967ec7be1296e3fc093c24c?context=explore

**Comment by Buwujiu** [comment]
Score is deployed in Prod, closing.
