### ISSUE TITLE
Create content for a SCORe page in overture.bio

### ISSUE THREAD

**Issue by Fgerthoffert** [overture-stack/score#79]
Requirement for: https://github.com/overture-stack/persona/issues/21

**Comment by andricDu** [comment]
# SCORe
**S**ecure **C**loud **O**bject **Re**pository 

SCORe is a system for providing an interface to control and provision access to raw genomic data sitting in object storage systems. 

Comprised of both a server and client component, the system allows for data custodians to gate access to their data and provision access to it, while end users will have access to advanced features such as parallel downloads and BAM slicing. 

The system currently supports any object storage system compatible with any of the following storage APIs and systems:
-	AWS S3
-	Azure Blob Storage
-	Google Cloud Storage

The use of the client is not required as the server component provides a RESTful API which returns signedURLs from the backing object store which allows any client to pull or upload data.

**Comment by andricDu** [comment]
@rosibaj what was the required length?

**Comment by rosibaj** [comment]
@andricDu I updated the wiki page template with this info, but we need some more key features and value propositions

https://wiki.oicr.on.ca/display/DCCSOFT/Score
